<div style="background:#E9FFF6; color:#440404; padding:8px; border-radius: 4px; text-align: center; font-weight: 500;">IFN619 - Data Analytics for Strategic Decision Makers</div>

# IFN619 :: B1-DataStructures - tutorial exercises

In [1]:
# import libraries
import pandas as pd
import numpy as np
import json
import requests

## Task 1: Brisbane Ferry Terminals
Purpose: save a long string as a `csv` file and read the `csv` file as a `pandas` `DataFrame`

Data are modified from [Ferry Terminal locations](https://data.brisbane.qld.gov.au/explore/dataset/ferry-terminals/information/)


**Step 1**: Save the `long_str` below into a `csv` file named `brisbane_ferry_terminals.csv` under the `data/` folder.

>Hint: to save a file instead of read a file, you can change the argument of `'r'` to `'w'` in the `open()` function. 

>`'r'` = 'read', `'w'` = 'write'

In [2]:
# Note: use triple quotes like ''' or """ to create a multi-line string in Python
long_str = '''
DESCRIPTION,STREETNAME,ADJ_PROPERTY_ADDRESS,SUBURB,LATITUDE,LATITUDE,LONGITUDE,STATUS,SERVICE_TYPE,PARKING,LIFT_ACCESS,ACCESSIBLE_PARKING,ACCESSIBLE_TOILET
UQ St Lucia ferry terminal,Sir William Macgregor Dr,342 CARMODY RD,ST LUCIA,"501,931.56",-27.497,153.02,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries
West End ferry terminal,Hoogley St,55 HOOGLEY ST,WEST END,"500,318.37",-27.49,153.003,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries
Guyatt Park ferry terminal,Macquarie St,46 HIRON ST,ST LUCIA,"500,216.72",-27.492,153.002,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries
Regatta ferry terminal,Coronation Dr,566 CORONATION DR,TOOWONG,"499,692.57",-27.483,152.997,INACTIVE,CityCat,No,No,No,Toilet available on CityCat ferries
Milton ferry terminal,Coronation Dr,299 CORONATION DR,MILTON,"500,543.38",-27.474,153.006,ACTIVE,CityCat,No,No,No,Toilet available on CityCat ferries
North Quay ferry terminal,Queens Wharf Rd,15 QUEENS WHARF RD,BRISBANE CITY,"502,226.49",-27.473,153.023,INACTIVE,"CityCat, CityHopper",No,Yes,No,Toilet available on CityCat ferries
QUT Gardens Point ferry terminal,Gardens Point Rd,59 GARDENS POINT RD,BRISBANE CITY,"502,591.80",-27.478,153.026,ACTIVE,CityCat,Yes - off-street,No,No,Toilet available on CityCat ferries
Maritime Museum ferry terminal,Lower River Tce,77 LOWER RIVER TCE,KANGAROO POINT,"502,851.34",-27.482,153.029,ACTIVE,CityHopper,Yes - on-street,No,Yes,No
Riverside ferry terminal,Eagle St,32 MACROSSAN ST,BRISBANE CITY,"503,088.35",-27.467,153.031,ACTIVE,"CityCat, CityHopper, Cross River Ferry",No,No,No,Toilet available on CityCat ferries
Holman Street ferry terminal,Holman St,126 HOLMAN ST,KANGAROO POINT,"503,310.01",-27.466,153.034,INACTIVE,"CityHopper, Cross River Ferry",Yes - on-street,No,Yes,No - Nearby in park
Howard Smith Wharves ferry terminal,Bowen Tce,5 BOUNDARY ST,FORTITUDE VALLEY,"503,711.33",-27.463,153.038,ACTIVE,CityHopper,Yes - off-street,Yes,No,No
Dockside ferry terminal,Ferry St,44 FERRY ST,KANGAROO POINT,"503,872.14",-27.472,153.039,ACTIVE,CityHopper,Yes,No,No,No
Sydney Street ferry terminal,Sydney St,112 OXLADE DR,NEW FARM,"504,167.97",-27.475,153.042,ACTIVE,"CityCat, CityHopper",Yes - on-street,No,No,Toilet available on CityCat ferries
Mowbray Park ferry terminal,Park Av,31 PARK AVE,EAST BRISBANE,"504,285.84",-27.477,153.043,ACTIVE,CityCat,Yes - off-street,No,Yes,Toilet available on CityCat ferries
New Farm Park ferry terminal,Brunswick St,1042 BRUNSWICK ST,NEW FARM,"505,202.80",-27.472,153.053,ACTIVE,CityCat,Yes - off-street,No,Yes,Toilet available on CityCat ferries
Hawthorne ferry terminal,Gordon St,14 GORDON ST,HAWTHORNE,"505,249.93",-27.461,153.053,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries
Bulimba ferry terminal,Oxford St,2 OXFORD ST,BULIMBA,"505,152.79",-27.451,153.052,ACTIVE,"CityCat, Cross River Ferry",Yes - on-street,No,Yes,Toilet available on CityCat ferries
Teneriffe ferry terminal,Commercial Rd,17 SKYRING TCE,TENERIFFE,"504,885.74",-27.452,153.049,ACTIVE,"CityCat, Cross River Ferry",Yes - on-street,No,No,Toilet available on CityCat ferries
Bretts Wharf ferry terminal,Kingsford Smith Dr,449 KINGSFORD SMITH DR,HAMILTON,"506,334.05",-27.44,153.064,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries
Apollo Road ferry terminal,Apollo St,3 BYRON ST,BULIMBA,"506,305.13",-27.443,153.064,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries
Northshore Hamilton ferry terminal,Macarthur Avenue,305 MACARTHUR AVE,HAMILTON,"508,280.43",-27.445,153.084,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries
South Bank ferry terminal,Clem Jones Promanade,153 STANLEY ST,SOUTH BRISBANE,"502,206.67",-27.476,153.022,ACTIVE,"CityCat, CityHopper",No,No,No,Toilet available on CityCat ferries
'''
# View the string
long_str

'\nDESCRIPTION,STREETNAME,ADJ_PROPERTY_ADDRESS,SUBURB,LATITUDE,LATITUDE,LONGITUDE,STATUS,SERVICE_TYPE,PARKING,LIFT_ACCESS,ACCESSIBLE_PARKING,ACCESSIBLE_TOILET\nUQ St Lucia ferry terminal,Sir William Macgregor Dr,342 CARMODY RD,ST LUCIA,"501,931.56",-27.497,153.02,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries\nWest End ferry terminal,Hoogley St,55 HOOGLEY ST,WEST END,"500,318.37",-27.49,153.003,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries\nGuyatt Park ferry terminal,Macquarie St,46 HIRON ST,ST LUCIA,"500,216.72",-27.492,153.002,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries\nRegatta ferry terminal,Coronation Dr,566 CORONATION DR,TOOWONG,"499,692.57",-27.483,152.997,INACTIVE,CityCat,No,No,No,Toilet available on CityCat ferries\nMilton ferry terminal,Coronation Dr,299 CORONATION DR,MILTON,"500,543.38",-27.474,153.006,ACTIVE,CityCat,No,No,No,Toilet available on CityCat ferries\nNorth Quay ferry terminal,Queens Wharf Rd,15 QUEENS WHARF RD,BRISBANE CITY,"502,226.49",-27.473,153.023,INACTIVE,"CityCat, CityHopper",No,Yes,No,Toilet available on CityCat ferries\nQUT Gardens Point ferry terminal,Gardens Point Rd,59 GARDENS POINT RD,BRISBANE CITY,"502,591.80",-27.478,153.026,ACTIVE,CityCat,Yes - off-street,No,No,Toilet available on CityCat ferries\nMaritime Museum ferry terminal,Lower River Tce,77 LOWER RIVER TCE,KANGAROO POINT,"502,851.34",-27.482,153.029,ACTIVE,CityHopper,Yes - on-street,No,Yes,No\nRiverside ferry terminal,Eagle St,32 MACROSSAN ST,BRISBANE CITY,"503,088.35",-27.467,153.031,ACTIVE,"CityCat, CityHopper, Cross River Ferry",No,No,No,Toilet available on CityCat ferries\nHolman Street ferry terminal,Holman St,126 HOLMAN ST,KANGAROO POINT,"503,310.01",-27.466,153.034,INACTIVE,"CityHopper, Cross River Ferry",Yes - on-street,No,Yes,No - Nearby in park\nHoward Smith Wharves ferry terminal,Bowen Tce,5 BOUNDARY ST,FORTITUDE VALLEY,"503,711.33",-27.463,153.038,ACTIVE,CityHopper,Yes - off-street,Yes,No,No\nDockside ferry terminal,Ferry St,44 FERRY ST,KANGAROO POINT,"503,872.14",-27.472,153.039,ACTIVE,CityHopper,Yes,No,No,No\nSydney Street ferry terminal,Sydney St,112 OXLADE DR,NEW FARM,"504,167.97",-27.475,153.042,ACTIVE,"CityCat, CityHopper",Yes - on-street,No,No,Toilet available on CityCat ferries\nMowbray Park ferry terminal,Park Av,31 PARK AVE,EAST BRISBANE,"504,285.84",-27.477,153.043,ACTIVE,CityCat,Yes - off-street,No,Yes,Toilet available on CityCat ferries\nNew Farm Park ferry terminal,Brunswick St,1042 BRUNSWICK ST,NEW FARM,"505,202.80",-27.472,153.053,ACTIVE,CityCat,Yes - off-street,No,Yes,Toilet available on CityCat ferries\nHawthorne ferry terminal,Gordon St,14 GORDON ST,HAWTHORNE,"505,249.93",-27.461,153.053,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries\nBulimba ferry terminal,Oxford St,2 OXFORD ST,BULIMBA,"505,152.79",-27.451,153.052,ACTIVE,"CityCat, Cross River Ferry",Yes - on-street,No,Yes,Toilet available on CityCat ferries\nTeneriffe ferry terminal,Commercial Rd,17 SKYRING TCE,TENERIFFE,"504,885.74",-27.452,153.049,ACTIVE,"CityCat, Cross River Ferry",Yes - on-street,No,No,Toilet available on CityCat ferries\nBretts Wharf ferry terminal,Kingsford Smith Dr,449 KINGSFORD SMITH DR,HAMILTON,"506,334.05",-27.44,153.064,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries\nApollo Road ferry terminal,Apollo St,3 BYRON ST,BULIMBA,"506,305.13",-27.443,153.064,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries\nNorthshore Hamilton ferry terminal,Macarthur Avenue,305 MACARTHUR AVE,HAMILTON,"508,280.43",-27.445,153.084,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries\nSouth Bank ferry terminal,Clem Jones Promanade,153 STANLEY ST,SOUTH BRISBANE,"502,206.67",-27.476,153.022,ACTIVE,"CityCat, CityHopper",No,No,No,Toilet available on CityCat ferries\n'

In [3]:
# write the string to a csv file named 'brisbane_ferry_terminals.csv' under 'data/'
with open('data/brisbane_ferry_terminals.csv', 'w') as file:
    file.write(long_str)

**Step 2**: Read the `csv` file you just saved as a DataFrame.

In [4]:
df = pd.read_csv('data/brisbane_ferry_terminals.csv')
df

,DESCRIPTION,STREETNAME,ADJ_PROPERTY_ADDRESS,SUBURB,LATITUDE,LATITUDE.1,LONGITUDE,STATUS,SERVICE_TYPE,PARKING,LIFT_ACCESS,ACCESSIBLE_PARKING,ACCESSIBLE_TOILET
0,UQ St Lucia ferry terminal,Sir William Macgregor Dr,342 CARMODY RD,ST LUCIA,"501,931.56",-27.497,153.020,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries
1,West End ferry terminal,Hoogley St,55 HOOGLEY ST,WEST END,"500,318.37",-27.490,153.003,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries
2,Guyatt Park ferry terminal,Macquarie St,46 HIRON ST,ST LUCIA,"500,216.72",-27.492,153.002,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries
3,Regatta ferry terminal,Coronation Dr,566 CORONATION DR,TOOWONG,"499,692.57",-27.483,152.997,INACTIVE,CityCat,No,No,No,Toilet available on CityCat ferries
4,Milton ferry terminal,Coronation Dr,299 CORONATION DR,MILTON,"500,543.38",-27.474,153.006,ACTIVE,CityCat,No,No,No,Toilet available on CityCat ferries
5,North Quay ferry terminal,Queens Wharf Rd,15 QUEENS WHARF RD,BRISBANE CITY,"502,226.49",-27.473,153.023,INACTIVE,"CityCat, CityHopper",No,Yes,No,Toilet available on CityCat ferries
6,QUT Gardens Point ferry terminal,Gardens Point Rd,59 GARDENS POINT RD,BRISBANE CITY,"502,591.80",-27.478,153.026,ACTIVE,CityCat,Yes - off-street,No,No,Toilet available on CityCat ferries
7,Maritime Museum ferry terminal,Lower River Tce,77 LOWER RIVER TCE,KANGAROO POINT,"502,851.34",-27.482,153.029,ACTIVE,CityHopper,Yes - on-street,No,Yes,No
8,Riverside ferry terminal,Eagle St,32 MACROSSAN ST,BRISBANE CITY,"503,088.35",-27.467,153.031,ACTIVE,"CityCat, CityHopper, Cross River Ferry",No,No,No,Toilet available on CityCat ferries
9,Holman Street ferry terminal,Holman St,126 HOLMAN ST,KANGAROO POINT,"503,310.01",-27.466,153.034,INACTIVE,"CityHopper, Cross River Ferry",Yes - on-street,No,Yes,No - Nearby in park
10,Howard Smith Wharves ferry terminal,Bowen Tce,5 BOUNDARY ST,FORTITUDE VALLEY,"503,711.33",-27.463,153.038,ACTIVE,CityHopper,Yes - off-street,Yes,No,No
11,Dockside ferry terminal,Ferry St,44 FERRY ST,KANGAROO POINT,"503,872.14",-27.472,153.039,ACTIVE,CityHopper,Yes,No,No,No
12,Sydney Street ferry terminal,Sydney St,112 OXLADE DR,NEW FARM,"504,167.97",-27.475,153.042,ACTIVE,"CityCat, CityHopper",Yes - on-street,No,No,Toilet available on CityCat ferries
13,Mowbray Park ferry terminal,Park Av,31 PARK AVE,EAST BRISBANE,"504,285.84",-27.477,153.043,ACTIVE,CityCat,Yes - off-street,No,Yes,Toilet available on CityCat ferries
14,New Farm Park ferry terminal,Brunswick St,1042 BRUNSWICK ST,NEW FARM,"505,202.80",-27.472,153.053,ACTIVE,CityCat,Yes - off-street,No,Yes,Toilet available on CityCat ferries
15,Hawthorne ferry terminal,Gordon St,14 GORDON ST,HAWTHORNE,"505,249.93",-27.461,153.053,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries
16,Bulimba ferry terminal,Oxford St,2 OXFORD ST,BULIMBA,"505,152.79",-27.451,153.052,ACTIVE,"CityCat, Cross River Ferry",Yes - on-street,No,Yes,Toilet available on CityCat ferries
17,Teneriffe ferry terminal,Commercial Rd,17 SKYRING TCE,TENERIFFE,"504,885.74",-27.452,153.049,ACTIVE,"CityCat, Cross River Ferry",Yes - on-street,No,No,Toilet available on CityCat ferries
18,Bretts Wharf ferry terminal,Kingsford Smith Dr,449 KINGSFORD SMITH DR,HAMILTON,"506,334.05",-27.440,153.064,ACTIVE,CityCat,Yes - on-street,No,Yes,Toilet available on CityCat ferries
19,Apollo Road ferry terminal,Apollo St,3 BYRON ST,BULIMBA,"506,305.13",-27.443,153.064,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries
20,Northshore Hamilton ferry terminal,Macarthur Avenue,305 MACARTHUR AVE,HAMILTON,"508,280.43",-27.445,153.084,ACTIVE,CityCat,Yes - on-street,No,No,Toilet available on CityCat ferries
21,South Bank ferry terminal,Clem Jones Promanade,153 STANLEY ST,SOUTH BRISBANE,"502,206.67",-27.476,153.022,ACTIVE,"CityCat, CityHopper",No,No,No,Toilet available on CityCat ferries

**Question 1**: 

1. How many ferry terminals have parking facilities? 
2. Provide a list of ferry terminals that have parking facilities.

In [5]:
# get a sense what are the parking conditions
df['PARKING'].value_counts()

# alternative
# df.groupby('PARKING').size()

PARKING
Yes - on-street     12
No                   5
Yes - off-street     4
Yes                  1
Name: count, dtype: int64

In [6]:
# number of terminals with parking facilities
((df['PARKING'] == 'Yes - on-street') | (df['PARKING'] == 'Yes - off-street') | (df['PARKING'] == 'Yes')).sum()

# alternative 1
# df[(df['PARKING'] == 'Yes - on-street') | (df['PARKING'] == 'Yes - off-street') | (df['PARKING'] == 'Yes')].shape[0]

# alternative 2
# (df['PARKING'] != 'No').sum()

np.int64(17)

In [7]:
# Dataframe include ferry terminals with parking facilities

df_parking = df[(df['PARKING'] == 'Yes - on-street') | (df['PARKING'] == 'Yes - off-street') | (df['PARKING'] == 'Yes')]

# Save the names of ferry terminals as a list
parking_list = df_parking['DESCRIPTION'].to_list()

# Display the list 
parking_list

['UQ St Lucia ferry terminal',
 'West End ferry terminal',
 'Guyatt Park ferry terminal',
 'QUT Gardens Point ferry terminal',
 'Maritime Museum ferry terminal',
 'Holman Street ferry terminal',
 'Howard Smith Wharves ferry terminal',
 'Dockside ferry terminal',
 'Sydney Street ferry terminal',
 'Mowbray Park ferry terminal',
 'New Farm Park ferry terminal',
 'Hawthorne ferry terminal',
 'Bulimba ferry terminal',
 'Teneriffe ferry terminal',
 'Bretts Wharf ferry terminal',
 'Apollo Road ferry terminal',
 'Northshore Hamilton ferry terminal']

**Question 2**: Which **CityCat** terminals are currently **INACTIVE**?

In [8]:
# which terminals are inactive?
df[df['STATUS'] == 'INACTIVE']

,DESCRIPTION,STREETNAME,ADJ_PROPERTY_ADDRESS,SUBURB,LATITUDE,LATITUDE.1,LONGITUDE,STATUS,SERVICE_TYPE,PARKING,LIFT_ACCESS,ACCESSIBLE_PARKING,ACCESSIBLE_TOILET
3,Regatta ferry terminal,Coronation Dr,566 CORONATION DR,TOOWONG,"499,692.57",-27.483,152.997,INACTIVE,CityCat,No,No,No,Toilet available on CityCat ferries
5,North Quay ferry terminal,Queens Wharf Rd,15 QUEENS WHARF RD,BRISBANE CITY,"502,226.49",-27.473,153.023,INACTIVE,"CityCat, CityHopper",No,Yes,No,Toilet available on CityCat ferries
9,Holman Street ferry terminal,Holman St,126 HOLMAN ST,KANGAROO POINT,"503,310.01",-27.466,153.034,INACTIVE,"CityHopper, Cross River Ferry",Yes - on-street,No,Yes,No - Nearby in park

In [9]:
# inactive citycat terminals
df[(df['STATUS'] == 'INACTIVE') & (df['SERVICE_TYPE'].str.contains('CityCat'))]

,DESCRIPTION,STREETNAME,ADJ_PROPERTY_ADDRESS,SUBURB,LATITUDE,LATITUDE.1,LONGITUDE,STATUS,SERVICE_TYPE,PARKING,LIFT_ACCESS,ACCESSIBLE_PARKING,ACCESSIBLE_TOILET
3,Regatta ferry terminal,Coronation Dr,566 CORONATION DR,TOOWONG,"499,692.57",-27.483,152.997,INACTIVE,CityCat,No,No,No,Toilet available on CityCat ferries
5,North Quay ferry terminal,Queens Wharf Rd,15 QUEENS WHARF RD,BRISBANE CITY,"502,226.49",-27.473,153.023,INACTIVE,"CityCat, CityHopper",No,Yes,No,Toilet available on CityCat ferries

---
## Task 2 (open-ended)
What other questions you want to find out about the Brisbane Ferry services? Use the Data Analytics Cycle approach on this dataset.

### Question
[write your question here]

### Analysis

In [10]:
# Your code here

### Visualisation

In [11]:
# Your code here

### Insights
[write your insights here]

---
## Task 3: How many different species of kingfishers in Queensland?

Purpose: read a `json` file from a website; save a `json` file; navigate through a `json` file.

The URL below is a subset of the Queensland wildlife database with information of family of "birds" in Queensland. 

Data source: [Qld WildNet Data API](https://www.data.qld.gov.au/dataset/qld-wildlife-data-api). 

You can use the [interactive documentation](https://wildnet-pub.science-data.qld.gov.au/docs#/) to navigate through the API to find the following information related to kingfishers:
- `kingdom_name`: Animalia
- `phylum_name`: Chordata
- `class_name`: Aves

In order to request species of kingfishers, we need to know the `family_name` of kingfishers first. Below, we use the request URL of all 'birds' in Queensland, and save the json file for Task 4.

In [12]:
bird_url = 'https://wildnet-pub.science-data.qld.gov.au/api/v1/families?class_name=Aves'

# Request the content from the web server
response = requests.get(bird_url)

# Preview the content
response.content

b'[{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"thornbills and gerygones","family_name":"Acanthizidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"birds of prey","order_name":"Falconiformes","family_common_name":"eagles, kites, goshawks","family_name":"Accipitridae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"reed-warblers","family_name":"Acrocephalidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"frogmouths and nightjars","order_name":"Caprimulgiformes","family_common_name":"owlet-nightjars","family_name":"Aegothelidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"larks","family_name":"Alaudidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"kingfishers and allies","order_name":"Coraciiformes","family_common_name":"kingfishers","family_name":"Alcedinidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"duck-like birds","order_name":"Anseriformes","family_common_name":"ducks, geese and swans","family_name":"Anatidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"cormorants, pelicans and allies","order_name":"Pelecaniformes","family_common_name":"darter","family_name":"Anhingidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"duck-like birds","order_name":"Anseriformes","family_common_name":"magpie goose","family_name":"Anseranatidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"swifts and swiftlets","order_name":"Apodiformes","family_common_name":"swifts and swiftlets","family_name":"Apodidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"herons, egretts, ibises and storks","order_name":"Ciconiiformes","family_common_name":"herons, egrets and bitterns","family_name":"Ardeidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"woodswallows, currawongs, butcherbirds and magpie","family_name":"Artamidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"scrub-birds","family_name":"Atrichornithidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"waders and gulls","order_name":"Charadriiformes","family_common_name":"stone-curlews","family_name":"Burhinidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"cockatoos and parrots","order_name":"Psittaciformes","family_common_name":"cockatoos and corellas","family_name":"Cacatuidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"cuckoo-shrikes and trillers","family_name":"Campephagidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"frogmouths and nightjars","order_name":"Caprimulgiformes","family_common_name":"nightjars","family_name":"Caprimulgidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"emus, cassowaries and allies","order_name":"Struthioniformes","family_common_name":"emus and cassowaries","family_name":"Casuariidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"waders and gulls","order_name":"Charadriiformes","family_common_name":"plovers, dotterel and lapwings","family_name":"Charadriidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"herons, egretts, ibises and storks","order_name":"Ciconiiformes","family_common_name":"storks","family_name":"Ciconiidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"quail-thrushes","family_name":"Cinclosomatidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"cisticolas","family_name":"Cisticolidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"treecreepers","family_name":"Climacteridae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"pigeons and doves","order_name":"Columbiformes","family_common_name":"pigeons and doves","family_name":"Columbidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"kingfishers and allies","order_name":"Coraciiformes","family_common_name":"rollers","family_name":"Coraciidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"chough and apostlebird","family_name":"Corcoracidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"crows and ravens","family_name":"Corvidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"cuckoos","order_name":"Cuculiformes","family_common_name":"cuckoos","family_name":"Cuculidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"bristlebirds","family_name":"Dasyornithidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"flowerpeckers","family_name":"Dicaeidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"drongos","family_name":"Dicruridae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"tube-nosed birds","order_name":"Procellariiformes","family_common_name":"albatrosses","family_name":"Diomedeidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"buntings","family_name":"Emberizidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"weaver finches","family_name":"Estrildidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"frogmouths and nightjars","order_name":"Caprimulgiformes","family_common_name":"eared nightjars","family_name":"Eurostopodidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"birds of prey","order_name":"Falconiformes","family_common_name":"falcons","family_name":"Falconidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"shriketits","family_name":"Falcunculidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"cormorants, pelicans and allies","order_name":"Pelecaniformes","family_common_name":"frigatebirds","family_name":"Fregatidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"old world finches","family_name":"Fringillidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"waders and gulls","order_name":"Charadriiformes","family_common_name":"pratincoles","family_name":"Glareolidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"rails, cranes, bustards and allies","order_name":"Gruiformes","family_common_name":"cranes","family_name":"Gruidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"waders and gulls","order_name":"Charadriiformes","family_common_name":"oystercatchers","family_name":"Haematopodidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"kingfishers and allies","order_name":"Coraciiformes","family_common_name":"kookaburras and kingfishers","family_name":"Halcyonidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"swallows and martins","family_name":"Hirundinidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"tube-nosed birds","order_name":"Procellariiformes","family_common_name":"northern storm-petrels","family_name":"Hydrobatidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"waders and gulls","order_name":"Charadriiformes","family_common_name":"jacanas","family_name":"Jacanidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"waders and gulls","order_name":"Charadriiformes","family_common_name":"gulls, terns and noddies","family_name":"Laridae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"grassbirds","family_name":"Locustellidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"boatbills","family_name":"Machaerirhynchidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"fairy-wrens, emu-wrens and grasswrens","family_name":"Maluridae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"Megaluridae","family_name":"Megaluridae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"megapodes and allies","order_name":"Galliformes","family_common_name":"megapodes","family_name":"Megapodiidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"honeyeaters and chats","family_name":"Meliphagidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"lyrebirds","family_name":"Menuridae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"kingfishers and allies","order_name":"Coraciiformes","family_common_name":"bee-eaters","family_name":"Meropidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"monarch and flycatchers","family_name":"Monarchidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"pipits and wagtails","family_name":"Motacillidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"old world flycatchers","family_name":"Muscicapidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"sunbirds","family_name":"Nectariniidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"perching birds","order_name":"Passeriformes","family_common_name":"sittellas","family_name":"Neosittidae"},{"kingdom_common_name":"animals","kingdom_name":"Animalia","phylum_common_name":"vertebrates, lancelets, tunicates","phylum_name":"Chordata","class_common_name":"birds","class_name":"Aves","order_common_name":"megapodes and allies","order_name":"Galliformes","family_common_name":"guineafowl","family_name":"Numididae"},{"kingdom_common_name":"animals","king

In [13]:
# Get the data as json from the response
bird_family_json = response.json()
# Preview the data
bird_family_json

[{'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'thornbills and gerygones',
  'family_name': 'Acanthizidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'birds of prey',
  'order_name': 'Falconiformes',
  'family_common_name': 'eagles, kites, goshawks',
  'family_name': 'Accipitridae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'reed-warblers',
  'family_name': 'Acrocephalidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'frogmouths and nightjars',
  'order_name': 'Caprimulgiformes',
  'family_common_name': 'owlet-nightjars',
  'family_name': 'Aegothelidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'larks',
  'family_name': 'Alaudidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'kingfishers and allies',
  'order_name': 'Coraciiformes',
  'family_common_name': 'kingfishers',
  'family_name': 'Alcedinidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'duck-like birds',
  'order_name': 'Anseriformes',
  'family_common_name': 'ducks, geese and swans',
  'family_name': 'Anatidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'cormorants, pelicans and allies',
  'order_name': 'Pelecaniformes',
  'family_common_name': 'darter',
  'family_name': 'Anhingidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'duck-like birds',
  'order_name': 'Anseriformes',
  'family_common_name': 'magpie goose',
  'family_name': 'Anseranatidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'swifts and swiftlets',
  'order_name': 'Apodiformes',
  'family_common_name': 'swifts and swiftlets',
  'family_name': 'Apodidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'herons, egretts, ibises and storks',
  'order_name': 'Ciconiiformes',
  'family_common_name': 'herons, egrets and bitterns',
  'family_name': 'Ardeidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'woodswallows, currawongs, butcherbirds and magpie',
  'family_name': 'Artamidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'scrub-birds',
  'family_name': 'Atrichornithidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'waders and gulls',
  'order_name': 'Charadriiformes',
  'family_common_name': 'stone-curlews',
  'family_name': 'Burhinidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'cockatoos and parrots',
  'order_name': 'Psittaciformes',
  'family_common_name': 'cockatoos and corellas',
  'family_name': 'Cacatuidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'cuckoo-shrikes and trillers',
  'family_name': 'Campephagidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'frogmouths and nightjars',
  'order_name': 'Caprimulgiformes',
  'family_common_name': 'nightjars',
  'family_name': 'Caprimulgidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'emus, cassowaries and allies',
  'order_name': 'Struthioniformes',
  'family_common_name': 'emus and cassowaries',
  'family_name': 'Casuariidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'waders and gulls',
  'order_name': 'Charadriiformes',
  'family_common_name': 'plovers, dotterel and lapwings',
  'family_name': 'Charadriidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'herons, egretts, ibises and storks',
  'order_name': 'Ciconiiformes',
  'family_common_name': 'storks',
  'family_name': 'Ciconiidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'quail-thrushes',
  'family_name': 'Cinclosomatidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'cisticolas',
  'family_name': 'Cisticolidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'treecreepers',
  'family_name': 'Climacteridae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'pigeons and doves',
  'order_name': 'Columbiformes',
  'family_common_name': 'pigeons and doves',
  'family_name': 'Columbidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'kingfishers and allies',
  'order_name': 'Coraciiformes',
  'family_common_name': 'rollers',
  'family_name': 'Coraciidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'chough and apostlebird',
  'family_name': 'Corcoracidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'crows and ravens',
  'family_name': 'Corvidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'cuckoos',
  'order_name': 'Cuculiformes',
  'family_common_name': 'cuckoos',
  'family_name': 'Cuculidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'bristlebirds',
  'family_name': 'Dasyornithidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'flowerpeckers',
  'family_name': 'Dicaeidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'drongos',
  'family_name': 'Dicruridae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'tube-nosed birds',
  'order_name': 'Procellariiformes',
  'family_common_name': 'albatrosses',
  'family_name': 'Diomedeidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'buntings',
  'family_name': 'Emberizidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'weaver finches',
  'family_name': 'Estrildidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'frogmouths and nightjars',
  'order_name': 'Caprimulgiformes',
  'family_common_name': 'eared nightjars',
  'family_name': 'Eurostopodidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'birds of prey',
  'order_name': 'Falconiformes',
  'family_common_name': 'falcons',
  'family_name': 'Falconidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'shriketits',
  'family_name': 'Falcunculidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'cormorants, pelicans and allies',
  'order_name': 'Pelecaniformes',
  'family_common_name': 'frigatebirds',
  'family_name': 'Fregatidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'old world finches',
  'family_name': 'Fringillidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'waders and gulls',
  'order_name': 'Charadriiformes',
  'family_common_name': 'pratincoles',
  'family_name': 'Glareolidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'rails, cranes, bustards and allies',
  'order_name': 'Gruiformes',
  'family_common_name': 'cranes',
  'family_name': 'Gruidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'waders and gulls',
  'order_name': 'Charadriiformes',
  'family_common_name': 'oystercatchers',
  'family_name': 'Haematopodidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'kingfishers and allies',
  'order_name': 'Coraciiformes',
  'family_common_name': 'kookaburras and kingfishers',
  'family_name': 'Halcyonidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'swallows and martins',
  'family_name': 'Hirundinidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'tube-nosed birds',
  'order_name': 'Procellariiformes',
  'family_common_name': 'northern storm-petrels',
  'family_name': 'Hydrobatidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'waders and gulls',
  'order_name': 'Charadriiformes',
  'family_common_name': 'jacanas',
  'family_name': 'Jacanidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'waders and gulls',
  'order_name': 'Charadriiformes',
  'family_common_name': 'gulls, terns and noddies',
  'family_name': 'Laridae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'grassbirds',
  'family_name': 'Locustellidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'boatbills',
  'family_name': 'Machaerirhynchidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'fairy-wrens, emu-wrens and grasswrens',
  'family_name': 'Maluridae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'Megaluridae',
  'family_name': 'Megaluridae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'megapodes and allies',
  'order_name': 'Galliformes',
  'family_common_name': 'megapodes',
  'family_name': 'Megapodiidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'honeyeaters and chats',
  'family_name': 'Meliphagidae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',
  'class_name': 'Aves',
  'order_common_name': 'perching birds',
  'order_name': 'Passeriformes',
  'family_common_name': 'lyrebirds',
  'family_name': 'Menuridae'},
 {'kingdom_common_name': 'animals',
  'kingdom_name': 'Animalia',
  'phylum_common_name': 'vertebrates, lancelets, tunicates',
  'phylum_name': 'Chordata',
  'class_common_name': 'birds',

In [14]:
# save the bird json file for later use in Task 4

# Dump the dict into a json string
qld_bird_json = json.dumps(bird_family_json)
# Write the json string to a file 
file_name = 'qld_bird_family.json'
with open(f"data/{file_name}","w") as fp:
    fp.write(qld_bird_json)

In [15]:
# how many families of birds are in Queensland?
len(bird_family_json)

104

You will notice that it seems all the contents are stored as a list, each item is a dictionary that contains one family of birds. Where are the kingfishers?

**Question 1**: display the **6th** item from the list, and save the information in a new `json` file named `qld_kingfishers_family.json` under the `data/` folder.

In [16]:
# Display the 6th item
qld_kf_family = bird_family_json[5]
qld_kf_family

{'kingdom_common_name': 'animals',
 'kingdom_name': 'Animalia',
 'phylum_common_name': 'vertebrates, lancelets, tunicates',
 'phylum_name': 'Chordata',
 'class_common_name': 'birds',
 'class_name': 'Aves',
 'order_common_name': 'kingfishers and allies',
 'order_name': 'Coraciiformes',
 'family_common_name': 'kingfishers',
 'family_name': 'Alcedinidae'}

Now we know the `family_name` for kingfishers, we then can get the request URL to get all the kingfisher species in Queensland in order to answer the following questions: 
1. How many species of kingfishers are in Queensland?
2. What are the species names of kingfishers in Queensland?

In [17]:
# Request URL (use Qld WildNet Data API documentation)
kingfishers_url = 'https://wildnet-pub.science-data.qld.gov.au/api/v1/species-list?family_name=Alcedinidae&page_size=1000&page_number=1'
kingfishers_url

'https://wildnet-pub.science-data.qld.gov.au/api/v1/species-list?family_name=Alcedinidae&page_size=1000&page_number=1'

In [18]:
# Extract the information from the url above, save the data as json
response_kf = requests.get(kingfishers_url)
kf_json = response_kf.json()
kf_json

[{'taxon_id': 1778,
  'scientific_name': 'Alcedo sp.',
  'kingdom_name': 'Animalia',
  'accepted_common_name': None,
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'U',
  'nca_code': None,
  'epbc_code': None,
  'matched_names': [{'name': 'alcesp.', 'name_type': 'DOE'},
   {'name': 'Alcedo sp.', 'name_type': 'SCI'}],
  'nca_desc': None,
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 0,
  'unconfirmed_sightings': 0,
  'specimen_sightings': 0,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1776,
  'scientific_name': 'Ceyx azureus',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'azure kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QAI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'azure kingfisher', 'name_type': 'ACO'},
   {'name': 'ceyxazur', 'name_type': 'DOE'},
   {'name': 'Ceyx azureus', 'name_type': 'SCI'},
   {'name': 'Alcedo azurea', 'name_type': 'SYN'},
   {'name': 'Ceyx azurea', 'name_type': 'SYN'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 984,
  'unconfirmed_sightings': 4115,
  'specimen_sightings': 36,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1777,
  'scientific_name': 'Ceyx pusillus',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'little kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QAI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'little kingfisher', 'name_type': 'ACO'},
   {'name': 'ceyxpusi', 'name_type': 'DOE'},
   {'name': 'Ceyx pusillus', 'name_type': 'SCI'},
   {'name': 'Alcedo pusilla', 'name_type': 'SYN'},
   {'name': 'Ceyx pusilla', 'name_type': 'SYN'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 85,
  'unconfirmed_sightings': 402,
  'specimen_sightings': 15,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1766,
  'scientific_name': 'Dacelo leachii',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'blue-winged kookaburra',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QAI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'blue-winged kookaburra', 'name_type': 'ACO'},
   {'name': 'barking jackass', 'name_type': 'COM'},
   {'name': 'howling jackass', 'name_type': 'COM'},
   {'name': 'daceleac', 'name_type': 'DOE'},
   {'name': 'Dacelo leachii', 'name_type': 'SCI'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 1335,
  'unconfirmed_sightings': 8831,
  'specimen_sightings': 53,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1767,
  'scientific_name': 'Dacelo novaeguineae',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'laughing kookaburra',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QA',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'laughing kookaburra', 'name_type': 'ACO'},
   {'name': 'dacenova', 'name_type': 'DOE'},
   {'name': 'Dacelo novaeguineae', 'name_type': 'SCI'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 7594,
  'unconfirmed_sightings': 39536,
  'specimen_sightings': 38,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1769,
  'scientific_name': 'Syma torotoro',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'yellow-billed kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QAI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'yellow-billed kingfisher', 'name_type': 'ACO'},
   {'name': 'symatoro', 'name_type': 'DOE'},
   {'name': 'Syma torotoro', 'name_type': 'SCI'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 49,
  'unconfirmed_sightings': 586,
  'specimen_sightings': 14,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 33859,
  'scientific_name': 'Tanysiptera hydrocharis',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'little paradise kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'VI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'little paradise kingfisher', 'name_type': 'ACO'},
   {'name': 'Aru Paradise-Kingfisher', 'name_type': 'COM'},
   {'name': 'Lesser Paradise-Kingfisher', 'name_type': 'COM'},
   {'name': 'Little Paradise-Kingfisher', 'name_type': 'COM'},
   {'name': 'tanyhydr', 'name_type': 'DOE'},
   {'name': 'Tanysiptera hydrocharis', 'name_type': 'SCI'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 1,
  'unconfirmed_sightings': 0,
  'specimen_sightings': 0,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1758,
  'scientific_name': 'Tanysiptera sylvia',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'buff-breasted paradise-kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QAI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'buff-breasted paradise-kingfisher',
    'name_type': 'ACO'},
   {'name': 'buff-breasted paradise kingfisher', 'name_type': 'COM'},
   {'name': 'white-tailed kingfisher', 'name_type': 'COM'},
   {'name': 'tanysylv', 'name_type': 'DOE'},
   {'name': 'Tanysiptera sylvia', 'name_type': 'SCI'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 217,
  'unconfirmed_sightings': 2160,
  'specimen_sightings': 47,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1760,
  'scientific_name': 'Todiramphus macleayii',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'forest kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QAI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'forest kingfisher', 'name_type': 'ACO'},
   {'name': 'todimacl', 'name_type': 'DOE'},
   {'name': 'Todiramphus macleayii', 'name_type': 'SCI'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 1950,
  'unconfirmed_sightings': 13470,
  'specimen_sightings': 73,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1761,
  'scientific_name': 'Todiramphus pyrrhopygius',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'red-backed kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QA',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'red-backed kingfisher', 'name_type': 'ACO'},
   {'name': 'todipyrr', 'name_type': 'DOE'},
   {'name': 'Todiramphus pyrrhopygius', 'name_type': 'SCI'},
   {'name': 'Todiramphus pyrrhopygia', 'name_type': 'SYN'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 794,
  'unconfirmed_sightings': 2653,
  'specimen_sightings': 17,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1762,
  'scientific_name': 'Todiramphus sanctus',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'sacred kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QAI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'sacred kingfisher', 'name_type': 'ACO'},
   {'name': 'todisanc', 'name_type': 'DOE'},
   {'name': 'Todiramphus sanctus', 'name_type': 'SCI'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 3311,
  'unconfirmed_sightings': 16842,
  'specimen_sightings': 30,
  'area_list_count': None,
  'date_last_seen': None},
 {'taxon_id': 1759,
  'scientific_name': 'Todiramphus sordidus',
  'kingdom_name': 'Animalia',
  'accepted_common_name': 'Torresian kingfisher',
  'class_name': 'Aves',
  'family_name': 'Alcedinidae',
  'sensitive': None,
  'con_sig': False,
  'superseded': False,
  'establishment_code': 'QAI',
  'nca_code': 'C',
  'epbc_code': None,
  'matched_names': [{'name': 'Torresian kingfisher', 'name_type': 'ACO'},
   {'name': 'black-masked kingfisher', 'name_type': 'COM'},
   {'name': 'collared kingfisher', 'name_type': 'COM'},
   {'name': 'mangrove collared kingfisher', 'name_type': 'COM'},
   {'name': 'mangrove kingfisher', 'name_type': 'COM'},
   {'name': 'sordid kingfisher', 'name_type': 'COM'},
   {'name': 'white-collared kingfisher', 'name_type': 'COM'},
   {'name': 'todisord', 'name_type': 'DOE'},
   {'name': 'Todiramphus sordidus', 'name_type': 'SCI'},
   {'name': 'Halcyon chloris sordida', 'name_type': 'SYN'},
   {'name': 'Halcyon sordidus', 'name_type': 'SYN'},
   {'name': 'Halcyon sordidus cooktowni', 'name_type': 'SYN'},
   {'name': 'Sauropatis chloris hyperpontia', 'name_type': 'SYN'},
   {'name': 'Sauropatis sordida colcloughi', 'name_type': 'SYN'},
   {'name': 'Todiramphus chloris', 'name_type': 'SYN'},
   {'name': 'Todiramphus chloris colcloughi', 'name_type': 'SYN'},
   {'name': 'Todiramphus chloris sordidus', 'name_type': 'SYN'},
   {'name': 'Todiramphus sordidus colcloughi', 'name_type': 'SYN'},
   {'name': 'Todiramphus sordidus sordidus', 'name_type': 'SYN'}],
  'nca_desc': 'Least concern',
  'epbc_desc': None,
  'area_type': None,
  'area_id': None,
  'confirmed_sightings': 475,
  'unconfirmed_sightings': 2825,
  'specimen_sightings': 26,
  'area_list_count': None,
  'date_last_seen': None}]

**Question 1**: How many species of kingfishers in Queensland?
>Hint: You can use `len([list])` to calculate how many items in a list.

In [19]:
# How many species of kingfishers in Queensland?
len(kf_json)

12

**Question 2**: What are the species names of kingfishers in Queensland?
>Hint: You need to use a for loop to extract the names

In [20]:
# What are the species names (and common names) of kingfishers in Queensland?
for item in kf_json:
    print(item['scientific_name'], f"({item['accepted_common_name']})")

Alcedo sp. (None)
Ceyx azureus (azure kingfisher)
Ceyx pusillus (little kingfisher)
Dacelo leachii (blue-winged kookaburra)
Dacelo novaeguineae (laughing kookaburra)
Syma torotoro (yellow-billed kingfisher)
Tanysiptera hydrocharis (little paradise kingfisher)
Tanysiptera sylvia (buff-breasted paradise-kingfisher)
Todiramphus macleayii (forest kingfisher)
Todiramphus pyrrhopygius (red-backed kingfisher)
Todiramphus sanctus (sacred kingfisher)
Todiramphus sordidus (Torresian kingfisher)

---
## Task 4 (open-ended)
Go back to the bird family json file and find another species that you are interested in, and look for more information from the chosen species. 
You can also check other kingdoms, classes or families from the [Qld WildNet Data API](https://www.data.qld.gov.au/dataset/qld-wildlife-data-api).